[package]
name = "pixel_sorting_rust"
version = "0.1.0"
authors = ["Hendrik Müller <hendrik.mueller@devboost.de>"]
edition = "2018"

[features]
multithread = []

[dependencies]
image = "0.23.5"
num-complex = "0.3.0"
itertools = "0.9.0"
threadpool = "1.8.1"
num_cpus = "1.13.0"
